# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170813_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
    ]
