# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20170813_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title_text',
            new_name='title',
        ),
    ]
