# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20170813_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(max_length=1000),
        ),
    ]
